include $(TOPDIR)/rules.mk

PKG_VERSION:=2.0.0-21
PKG_RELEASE:=1

LUCI_TITLE:=LuCI support for Frpc
LUCI_DEPENDS:=+libc
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
